kit:
  name: "Cloudera Hadoop"
  link: https://github.com/griddynamics/component-hadoop
  applications:
    - name: "CDH Main"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/component-hadoop.yml"
    - name: "Cloudera Flume"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-flume.yml"
    - name: "Cloudera Hadoop"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-hadoop.yml"
    - name: "Cloudera Manager"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-manager.yml"
    - name: "Cloudera Pig"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-pig.yml"
    - name: "Cloudera Solr"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-solr.yml"
    - name: "Cloudera Yarn"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-yarn.yml"
    - name: "Cloudera Spark"
      manifest: "https://raw.github.com/griddynamics/component-hadoop/2.6-43p/cloudera-spark.yml"
  provider:
    name: "tonomi"
    link: http://tonomi.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * CloudServers account;
        * Ports 7180, 60010, 50030, 50070, 8888 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.
